## POSTTEST 4 KB

Nama  : Patricia Chandra

NIM   : 2009106030

Kelas : Informatika A

## Split Training Set dan Testing Set (70% dan 30%)

In [63]:
from sklearn.model_selection import train_test_split
import pandas as pd

In [64]:
df = pd.read_csv('Top 2000 Universities of the World - Sheet1.csv')

In [65]:
df.head(12)

World Rank                            Institution         Country  \
0            1                     Harvard University             USA   
1            2  Massachusetts Institute of Technology             USA   
2            3                    Stanford University             USA   
3            4                University of Cambridge  United Kingdom   
4            5                   University of Oxford  United Kingdom   
5            6                   Princeton University             USA   
6            7                    Columbia University             USA   
7            8                  University of Chicago             USA   
8            9             University of Pennsylvania             USA   
9           10                        Yale University             USA   
10          11     California Institute of Technology             USA   
11          12     University of California, Berkeley             USA   

    National Rank Quality of Education Rank Alumni Employment Rank  \
0               1                         1                      1   
1               2                         4                     12   
2               3                        10                      4   
3               1                         3                     25   
4               2                         7                     27   
5               4                         5                     15   
6               5                        11                     14   
7               6                         8                     16   
8               7                        14                     10   
9               8                         6                     36   
10              9                         2                    111   
11             10                         9                     60   

   Quality of Faculty Rank Research Performance Rank  Score  
0                        1                         1  100.0  
1                        2                         8   96.7  
2                        3                         2   95.1  
3                        4                        10   94.1  
4                        9                         4   93.3  
5                        7                        70   92.6  
6                       10                        15   92.0  
7                       27                        22   91.5  
8                       42                        12   91.1  
9                       13                        20   90.7  
10                       8                        75   90.4  
11                       5                        13   90.1

In [32]:
X = df.iloc[:,:-1] # target
Y = df.iloc[:,-1] # fitur

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

In [34]:
print("Dimensi X_train : ", X_train.shape)
print("Dimensi X_train : ", X_test.shape)
print("Dimensi Y_train : ", Y_train.shape)
print("Dimensi Y_test : ", Y_test.shape)

Dimensi X_train :  (1400, 8)
Dimensi X_train :  (600, 8)
Dimensi Y_train :  (1400,)
Dimensi Y_test :  (600,)


## Normalisasi

In [35]:
from sklearn.preprocessing import MinMaxScaler

In [36]:
mms = MinMaxScaler()

In [37]:
x_scaled = mms.fit_transform(df[['Score']])

In [38]:
data_normalization = pd.DataFrame(x_scaled)
data_normalization.head(10)

0
0  1.000000
1  0.903790
2  0.857143
3  0.827988
4  0.804665
5  0.784257
6  0.766764
7  0.752187
8  0.740525
9  0.728863

## Copy Database

In [39]:
df.to_csv("normalisasi.csv",index=False)

## Standarisasi

In [66]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [41]:
ss = StandardScaler()

Scaled_data = ss.fit_transform(df[['World Rank','National Rank','Score']])

In [42]:
print("Nilai Data Sebelum Scaling : ")
print(df[['World Rank','National Rank','Score']])

print("\n\nNilai Standar Deviasi : ")
print(np.std(df[['World Rank','National Rank','Score']]))

Nilai Data Sebelum Scaling : 
      World Rank  National Rank  Score
0              1              1  100.0
1              2              2   96.7
2              3              3   95.1
3              4              1   94.1
4              5              2   93.3
...          ...            ...    ...
1995        1996             56   65.8
1996        1997            275   65.7
1997        1998            276   65.7
1998        1999             53   65.7
1999        2000            277   65.7

[2000 rows x 3 columns]


Nilai Standar Deviasi : 
World Rank       577.350197
National Rank     83.107830
Score              5.078525
dtype: float64


In [43]:
print("Nilai Data setelah scaling : ")
print(Scaled_data)

print("\n\nNilai standar deviasi : ")
print(np.std(Scaled_data))

Nilai Data setelah scaling : 
[[-1.731185   -0.80044202  5.59484351]
 [-1.72945295 -0.78840946  4.94504848]
 [-1.7277209  -0.7763769   4.62999634]
 ...
 [ 1.7277209   2.50851212 -1.15908665]
 [ 1.72945295 -0.17474888 -1.15908665]
 [ 1.731185    2.52054468 -1.15908665]]


Nilai standar deviasi : 
1.0


## Copy Database

In [44]:
df.to_csv("standarisasi.csv",index=False)

## Data Cleaning dengan nilai null

In [75]:
from sklearn.impute import SimpleImputer

In [46]:
df.isna().sum()

World Rank                   0
Institution                  0
Country                      0
National Rank                0
Quality of Education Rank    0
Alumni Employment Rank       0
Quality of Faculty Rank      0
Research Performance Rank    0
Score                        0
dtype: int64

In [59]:
df.iloc[3,0] = np.nan # karena dataset tidak terdeteksi nilai null, maka dibuatlah nilai null

In [60]:
df.isna().sum() # mengecek apakah nilai telah terganti menjadi null

World Rank                   1
Institution                  0
Country                      1
National Rank                0
Quality of Education Rank    0
Alumni Employment Rank       0
Quality of Faculty Rank      0
Research Performance Rank    0
Score                        0
dtype: int64

## Cara SimpleImputer

In [84]:
df.iloc[3,8] = np.nan
df.isna().sum()

World Rank                   0
Institution                  0
Country                      0
National Rank                0
Quality of Education Rank    0
Alumni Employment Rank       0
Quality of Faculty Rank      0
Research Performance Rank    0
Score                        1
dtype: int64

In [85]:
imputer = SimpleImputer(strategy = 'mean')

In [86]:
df["Score"] = imputer.fit_transform(df[["Score"]])

In [87]:
df.isna().sum() # untuk mengecek apakah data null telah hilang

World Rank                   0
Institution                  0
Country                      0
National Rank                0
Quality of Education Rank    0
Alumni Employment Rank       0
Quality of Faculty Rank      0
Research Performance Rank    0
Score                        0
dtype: int64

## Data Cleaning dengan nilai duplikat

In [102]:
df = pd.read_csv('dataset duplikat.csv')

In [103]:
df[df.duplicated()] # untuk mengecek apakah terdapat nilai duplikat didalam dataset

World Rank          Institution Country  National Rank  \
12          7  Columbia University     USA            5.0   

   Quality of Education Rank Alumni Employment Rank Quality of Faculty Rank  \
12                        11                     14                      10   

   Research Performance Rank  Score  
12                        15   92.0

In [104]:
df.drop_duplicates(inplace = True)

In [105]:
df[df.duplicated()] # untuk mengecek apakah nilai tersebut telah terhapus atau tidak

Empty DataFrame
Columns: [World Rank, Institution, Country, National Rank, Quality of Education Rank, Alumni Employment Rank, Quality of Faculty Rank, Research Performance Rank, Score]
Index: []

## Ganti tipe data salah satu attribute angka

In [93]:
from sklearn.preprocessing import OrdinalEncoder

In [94]:
df.head(12) # melihat kondisi awal dataset

World Rank                            Institution         Country  \
0            1                     Harvard University             USA   
1            2  Massachusetts Institute of Technology             USA   
2            3                    Stanford University             USA   
3            4                University of Cambridge  United Kingdom   
4            5                   University of Oxford  United Kingdom   
5            6                   Princeton University             USA   
6            7                    Columbia University             USA   
7            8                  University of Chicago             USA   
8            9             University of Pennsylvania             USA   
9           10                        Yale University             USA   
10          11     California Institute of Technology             USA   
11          12     University of California, Berkeley             USA   

    National Rank Quality of Education Rank Alumni Employment Rank  \
0               1                         1                      1   
1               2                         4                     12   
2               3                        10                      4   
3               1                         3                     25   
4               2                         7                     27   
5               4                         5                     15   
6               5                        11                     14   
7               6                         8                     16   
8               7                        14                     10   
9               8                         6                     36   
10              9                         2                    111   
11             10                         9                     60   

   Quality of Faculty Rank Research Performance Rank  Score  
0                        1                         1  100.0  
1                        2                         8   96.7  
2                        3                         2   95.1  
3                        4                        10   92.5  
4                        9                         4   93.3  
5                        7                        70   92.6  
6                       10                        15   92.0  
7                       27                        22   91.5  
8                       42                        12   91.1  
9                       13                        20   90.7  
10                       8                        75   90.4  
11                       5                        13   90.1

In [95]:
encoder = OrdinalEncoder()
df["Country_encoded"] = encoder.fit_transform(df[["Country"]])
df.head(12)

World Rank                            Institution         Country  \
0            1                     Harvard University             USA   
1            2  Massachusetts Institute of Technology             USA   
2            3                    Stanford University             USA   
3            4                University of Cambridge  United Kingdom   
4            5                   University of Oxford  United Kingdom   
5            6                   Princeton University             USA   
6            7                    Columbia University             USA   
7            8                  University of Chicago             USA   
8            9             University of Pennsylvania             USA   
9           10                        Yale University             USA   
10          11     California Institute of Technology             USA   
11          12     University of California, Berkeley             USA   

    National Rank Quality of Education Rank Alumni Employment Rank  \
0               1                         1                      1   
1               2                         4                     12   
2               3                        10                      4   
3               1                         3                     25   
4               2                         7                     27   
5               4                         5                     15   
6               5                        11                     14   
7               6                         8                     16   
8               7                        14                     10   
9               8                         6                     36   
10              9                         2                    111   
11             10                         9                     60   

   Quality of Faculty Rank Research Performance Rank  Score  Country_encoded  
0                        1                         1  100.0             85.0  
1                        2                         8   96.7             85.0  
2                        3                         2   95.1             85.0  
3                        4                        10   92.5             89.0  
4                        9                         4   93.3             89.0  
5                        7                        70   92.6             85.0  
6                       10                        15   92.0             85.0  
7                       27                        22   91.5             85.0  
8                       42                        12   91.1             85.0  
9                       13                        20   90.7             85.0  
10                       8                        75   90.4             85.0  
11                       5                        13   90.1             85.0

## One Hot Encoding

In [96]:
from sklearn.preprocessing import OneHotEncoder

In [97]:
df = pd.read_csv('Top 2000 Universities of the World - Sheet1.csv')

In [100]:
onehotencoder = OneHotEncoder(sparse = False)
Country_encoded_2 = onehotencoder.fit_transform(df[["Country"]])

In [101]:
dfEn = pd.DataFrame(Country_encoded_2)
df = df.join(dfEn)

df.head(12)

World Rank                            Institution         Country  \
0            1                     Harvard University             USA   
1            2  Massachusetts Institute of Technology             USA   
2            3                    Stanford University             USA   
3            4                University of Cambridge  United Kingdom   
4            5                   University of Oxford  United Kingdom   
5            6                   Princeton University             USA   
6            7                    Columbia University             USA   
7            8                  University of Chicago             USA   
8            9             University of Pennsylvania             USA   
9           10                        Yale University             USA   
10          11     California Institute of Technology             USA   
11          12     University of California, Berkeley             USA   

    National Rank Quality of Education Rank Alumni Employment Rank  \
0               1                         1                      1   
1               2                         4                     12   
2               3                        10                      4   
3               1                         3                     25   
4               2                         7                     27   
5               4                         5                     15   
6               5                        11                     14   
7               6                         8                     16   
8               7                        14                     10   
9               8                         6                     36   
10              9                         2                    111   
11             10                         9                     60   

   Quality of Faculty Rank Research Performance Rank  Score    0  ...   85  \
0                        1                         1  100.0  0.0  ...  1.0   
1                        2                         8   96.7  0.0  ...  1.0   
2                        3                         2   95.1  0.0  ...  1.0   
3                        4                        10   94.1  0.0  ...  0.0   
4                        9                         4   93.3  0.0  ...  0.0   
5                        7                        70   92.6  0.0  ...  1.0   
6                       10                        15   92.0  0.0  ...  1.0   
7                       27                        22   91.5  0.0  ...  1.0   
8                       42                        12   91.1  0.0  ...  1.0   
9                       13                        20   90.7  0.0  ...  1.0   
10                       8                        75   90.4  0.0  ...  1.0   
11                       5                        13   90.1  0.0  ...  1.0   

     86   87   88   89   90   91   92   93   94  
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
4   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[12 rows x 104 columns]