## Posttest KB 7

Nama : Patricia Chandra

NIM : 2009106030

Kelas : Informatika A

1. Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [15]:
import tensorflow as tf

In [20]:
random_tensor = tf.Variable(tf.random.normal([5,5], mean=2, stddev=1, dtype=tf.float32, seed=30))
random_tensor.read_value().numpy()

array([[ 1.0221016 ,  2.1487036 ,  1.2131    ,  2.3831239 , -0.26141548],
       [ 1.392834  ,  3.2047813 ,  3.9090552 ,  1.4396985 ,  2.2059417 ],
       [ 2.6110075 ,  2.8681412 ,  1.5272284 ,  1.878454  ,  1.5347662 ],
       [ 1.9213053 ,  2.2337909 ,  2.069285  ,  3.6110878 ,  0.53981936],
       [ 1.2902892 ,  0.8324944 ,  1.369707  , -0.57819724,  2.4647884 ]],
      dtype=float32)

## 

2. Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [21]:
list = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]

In [22]:
prime_tensor = tf.Variable((tf.convert_to_tensor(list, dtype=tf.float32)))
prime_tensor.read_value().numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

## 

3. Tampilkan dimensi dari kedua variable tersebut

In [23]:
print(random_tensor.shape)
print(prime_tensor.shape)

(5, 5)
(5, 5)


## 

4. Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [35]:
# Pertambahan
tf.add(random_tensor,prime_tensor).numpy()

array([[ 3.0221016,  5.1487036,  6.2131   ,  9.383123 , 10.7385845],
       [14.392834 , 20.20478  , 22.909056 , 24.4397   , 31.205942 ],
       [33.611008 , 39.86814  , 42.52723  , 44.878452 , 48.534767 ],
       [54.921307 , 61.23379  , 63.069286 , 70.611084 , 71.53982  ],
       [74.29029  , 79.8325   , 84.369705 , 88.42181  , 99.46479  ]],
      dtype=float32)

In [36]:
# Pengurangan
tf.subtract(random_tensor,prime_tensor).numpy()

array([[ -0.97789836,  -0.8512964 ,  -3.7869    ,  -4.616876  ,
        -11.2614155 ],
       [-11.607166  , -13.795218  , -15.090944  , -21.5603    ,
        -26.794058  ],
       [-28.388992  , -34.13186   , -39.47277   , -41.121548  ,
        -45.465233  ],
       [-51.078693  , -56.76621   , -58.930714  , -63.388912  ,
        -70.46018   ],
       [-71.70971   , -78.1675    , -81.630295  , -89.57819   ,
        -94.53521   ]], dtype=float32)

In [37]:
# Perkalian
tf.multiply(random_tensor,prime_tensor).numpy()

array([[  2.0442033,   6.4461107,   6.0655   ,  16.681868 ,  -2.8755703],
       [ 18.106842 ,  54.48128  ,  74.27205  ,  33.113064 ,  63.97231  ],
       [ 80.94123  , 106.12122  ,  62.616364 ,  80.77352  ,  72.13401  ],
       [101.82918  , 131.79366  , 126.22638  , 241.94289  ,  38.327175 ],
       [ 94.19111  ,  65.76706  , 113.68568  , -51.459553 , 239.08447  ]],
      dtype=float32)

In [38]:
# Pembagian
tf.divide(random_tensor,prime_tensor).numpy()

array([[ 0.5110508 ,  0.7162345 ,  0.24261999,  0.34044626, -0.02376504],
       [ 0.10714107,  0.18851654,  0.20573975,  0.06259558,  0.07606696],
       [ 0.08422605,  0.07751733,  0.03724947,  0.04368497,  0.0326546 ],
       [ 0.03625104,  0.03786086,  0.0339227 ,  0.05389683,  0.00760309],
       [ 0.01767519,  0.0105379 ,  0.01650249, -0.0064966 ,  0.02541019]],
      dtype=float32)

In [39]:
# Pemangkatan
tf.pow(random_tensor,prime_tensor).numpy()

array([[ 1.0446918e+00,  9.9204073e+00,  2.6271384e+00,  4.3654230e+02,
        -3.8962278e-07],
       [ 7.4249146e+01,  3.9680099e+08,  1.7756784e+11,  4.3676255e+03,
         9.2093030e+09],
       [ 8.3377998e+12,  8.5353121e+16,  3.4678724e+07,  5.9350444e+11,
         5.5460602e+08],
       [ 1.0730209e+15,  3.9220058e+20,  1.8409322e+19,  2.3001132e+37,
         9.7642829e-20],
       [ 1.2026926e+08,  5.1300719e-07,  2.1882490e+11, -6.6798288e-22,
         1.0060645e+38]], dtype=float32)

## 

5. Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [29]:
tf.argmax(random_tensor, axis=0).numpy()

array([2, 1, 1, 3, 4], dtype=int64)

In [30]:
tf.argmin(random_tensor, axis=0).numpy()

array([0, 4, 0, 4, 0], dtype=int64)

## 

6. Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [31]:
# Sebelum
print(f"Size Awal : {random_tensor.shape} {prime_tensor.shape}" )

Size Awal : (5, 5) (5, 5)


In [32]:
# Setelah
concat_tensor_1 = tf.concat([random_tensor, prime_tensor], axis=0)
concat_tensor_2 = tf.concat([random_tensor, prime_tensor], axis=1)
print(f"Size yang sudah di concat (axis = 0) : {concat_tensor_1.shape}")
print(f"Size yang sudah di concat (axis = 1) : {concat_tensor_2.shape}")

Size yang sudah di concat (axis = 0) : (10, 5)
Size yang sudah di concat (axis = 1) : (5, 10)


## 

7. Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [33]:
# Sorting random_tensor secara descending
tf.sort(random_tensor, direction="DESCENDING").numpy()

array([[ 2.3831239 ,  2.1487036 ,  1.2131    ,  1.0221016 , -0.26141548],
       [ 3.9090552 ,  3.2047813 ,  2.2059417 ,  1.4396985 ,  1.392834  ],
       [ 2.8681412 ,  2.6110075 ,  1.878454  ,  1.5347662 ,  1.5272284 ],
       [ 3.6110878 ,  2.2337909 ,  2.069285  ,  1.9213053 ,  0.53981936],
       [ 2.4647884 ,  1.369707  ,  1.2902892 ,  0.8324944 , -0.57819724]],
      dtype=float32)

In [34]:
# Sorting random_tensor secara descending
tf.sort(prime_tensor, direction="DESCENDING").numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)